CREATE TABLE [dbo].[usuarios]
(
		id BIGINT NOT NULL IDENTITY(0,1),
	  email VARCHAR(45) NOT NULL UNIQUE,
	  password VARCHAR(150) NOT NULL,
	  name VARCHAR(45) NOT NULL,
	  birthDate DATE NULL,
	  gender CHAR NULL DEFAULT 'M',
	  active BIT NOT NULL DEFAULT 1,
	  registrationDate SMALLDATETIME NOT NULL DEFAULT SYSDATETIME(),
	  country VARCHAR(45) NOT NULL,
	  PRIMARY KEY (id)
)
