CREATE TABLE [dbo].[usuarios]
(
id VARCHAR(50) PRIMARY KEY DEFAULT NEWID(),
email VARCHAR(45) UNIQUE NOT NULL,
password VARCHAR(150) NOT NULL,
name VARCHAR(45) NOT NULL,
birthDate DATE NULL,
gender BIT NULL,
active BIT NOT NULL DEFAULT 1,
country VARCHAR(45) NOT NULL,
registrationDate DATE DEFAULT GETDATE(),
updateDate DATE,
deleteDate DATE
)
